# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'dashboard_user_active_idx') THEN
                        ALTER INDEX dashboard_user_active_idx RENAME TO dashboard_u_user_id_c45649_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'dashboard_user_expires_idx') THEN
                        ALTER INDEX dashboard_user_expires_idx RENAME TO dashboard_u_user_id_2f4ce5_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
