# Generated by Django 5.0 on 2026-06-09 10:35

import apps.project_control.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('boq', 'BOQ'), ('tender', 'Tender'), ('contract', 'Contract'), ('change_order', 'Change Order'), ('drawing', 'Drawing'), ('progress_report', 'Progress Report'), ('minutes', 'Meeting Minutes'), ('specification', 'Specification'), ('other', 'Other')], default='other', max_length=24)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(max_length=512, upload_to=apps.project_control.models._document_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('done', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('parse_error', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_documents', to='core.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_control_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('estimate', 'Internal Estimate'), ('tender', 'Tender Submitted'), ('awarded', 'Awarded / Contract'), ('baseline', 'Baseline (locked)'), ('revised', 'Revised')], default='estimate', max_length=20)),
                ('source', models.CharField(choices=[('excel', 'Excel BOQ import'), ('manual', 'Manual entry'), ('finance', 'Finance invoice sync'), ('ai_takeoff', 'AI Take-Off')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('snapshot_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_control_estimates_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='core.project')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_estimates', to='project_control.projectdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=12)),
                ('delta_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('delta_currency', models.CharField(default='AED', max_length=8)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('reviewed', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='detected', max_length=12)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='core.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_control_changes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_changes', to='project_control.projectdocument')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='WBSNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='e.g. 1.2.3', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_control.wbsnode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_nodes', to='core.project')),
            ],
            options={
                'ordering': ['project', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateField()),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpi', models.FloatField(blank=True, null=True)),
                ('spi', models.FloatField(blank=True, null=True)),
                ('eac', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('computed', 'Computed from tasks/invoices'), ('finance', 'Finance invoice sync')], default='manual', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='core.project')),
            ],
            options={
                'ordering': ['project', '-period_end'],
                'indexes': [models.Index(fields=['project', '-period_end'], name='project_con_project_141237_idx')],
                'unique_together': {('project', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('wbs_code', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('discipline', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('source_row', models.JSONField(blank=True, default=dict, help_text='Raw row captured from import')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='project_control.estimate')),
            ],
            options={
                'ordering': ['estimate', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['estimate', 'wbs_code'], name='project_con_estimat_9cada8_idx'), models.Index(fields=['estimate', 'discipline'], name='project_con_estimat_d944b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'kind'], name='project_con_project_be62e4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', '-created_at'], name='project_con_project_64a0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['project', 'kind'], name='project_con_project_6fd31e_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['project', 'status'], name='project_con_project_1e2a83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('project', 'kind', 'version')},
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['project', 'status'], name='project_con_project_3ac5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['project', '-detected_at'], name='project_con_project_26a66a_idx'),
        ),
        migrations.AddIndex(
            model_name='wbsnode',
            index=models.Index(fields=['project', 'level'], name='project_con_project_a23189_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wbsnode',
            unique_together={('project', 'code')},
        ),
    ]
