# Generated by Django 5.0 on 2026-06-29 17:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('emirates_id', models.CharField(blank=True, default='', max_length=32)),
                ('mol_no', models.CharField(blank=True, default='', max_length=32)),
                ('iban', models.CharField(blank=True, default='', max_length=64)),
                ('bank_name', models.CharField(blank=True, default='', max_length=128)),
                ('routing_code', models.CharField(blank=True, default='', max_length=64)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('discipline', models.CharField(blank=True, default='', max_length=128)),
                ('designation', models.CharField(blank=True, default='', max_length=128)),
                ('grade', models.CharField(blank=True, default='', max_length=128)),
                ('nationality_group', models.CharField(blank=True, default='', max_length=64)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('housing', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('home_leave', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('default_payment_mode', models.CharField(choices=[('WPS', 'WPS'), ('WPS-RSI', 'WPS – RSI'), ('BANK_TRANSFER', 'Bank Transfer'), ('BANK_TRANSFER_RSI', 'Bank Transfer – RSI'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='WPS', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_employees_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Employee',
                'db_table': 'payroll_engine_employee',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('cycle_code', models.CharField(db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('hr_approved', 'HR Approved'), ('finance_approved', 'Finance Approved'), ('released', 'Released')], db_index=True, default='draft', max_length=32)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('finance_approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_finance_approved', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_hr_approved', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'db_table': 'payroll_engine_run',
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.CreateModel(
            name='PayrollWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_engine_workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='payroll_engine.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Workflow Log',
                'db_table': 'payroll_engine_workflow_log',
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('housing', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('home_leave', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_mode', models.CharField(choices=[('WPS', 'WPS'), ('WPS-RSI', 'WPS – RSI'), ('BANK_TRANSFER', 'Bank Transfer'), ('BANK_TRANSFER_RSI', 'Bank Transfer – RSI'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='WPS', max_length=32)),
                ('snapshot_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_department', models.CharField(blank=True, default='', max_length=128)),
                ('snapshot_designation', models.CharField(blank=True, default='', max_length=128)),
                ('snapshot_iban', models.CharField(blank=True, default='', max_length=64)),
                ('snapshot_joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('hr_approved', 'HR Approved'), ('finance_approved', 'Finance Approved'), ('released', 'Released')], db_index=True, default='draft', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll_engine.payrollemployee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll_engine.payrollrun')),
            ],
            options={
                'verbose_name': 'Payslip',
                'db_table': 'payroll_engine_payslip',
                'ordering': ('snapshot_full_name',),
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_year', models.PositiveSmallIntegerField(db_index=True)),
                ('target_month', models.PositiveSmallIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=16)),
                ('component_code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll_engine.payrollemployee')),
                ('applied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='payroll_engine.payslip')),
            ],
            options={
                'verbose_name': 'Payroll Adjustment',
                'db_table': 'payroll_engine_adjustment',
                'ordering': ('-target_year', '-target_month', 'employee'),
            },
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], db_index=True, max_length=16)),
                ('component_code', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('source', models.CharField(choices=[('auto', 'Auto-generated'), ('manual', 'Manual entry'), ('excel', 'Excel upload'), ('adjustment', 'Adjustment')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_line_items_created', to=settings.AUTH_USER_MODEL)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll_engine.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Line Item',
                'db_table': 'payroll_engine_line_item',
                'ordering': ('kind', 'component_code'),
            },
        ),
        migrations.AddIndex(
            model_name='payrollemployee',
            index=models.Index(fields=['department', 'is_active'], name='payroll_eng_departm_1d3365_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollemployee',
            index=models.Index(fields=['is_active', 'employee_no'], name='payroll_eng_is_acti_bf8348_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='uq_payroll_run_year_month'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['run', 'status'], name='payroll_eng_run_id_9fc117_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='uq_payslip_run_employee'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['target_year', 'target_month', 'status'], name='payroll_eng_target__a97b42_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['employee', 'status'], name='payroll_eng_employe_ba379a_idx'),
        ),
        migrations.AddIndex(
            model_name='paysliplineitem',
            index=models.Index(fields=['payslip', 'kind'], name='payroll_eng_payslip_83c8c1_idx'),
        ),
    ]
