# Generated by Django 5.0 on 2026-06-30 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0002_add_employee_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(help_text='Human-readable source name e.g. "ValueFrame", "Sympa".', max_length=64)),
                ('source_profile', models.CharField(default='auto', help_text='Parser profile key from catalog.COMPARISON_PROFILES.', max_length=32)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='payroll_engine.payrollrun')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Comparison',
                'db_table': 'payroll_engine_comparison',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PayrollComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_employee_no', models.CharField(blank=True, default='', max_length=64)),
                ('external_name', models.CharField(blank=True, default='', max_length=255)),
                ('matched_by', models.CharField(blank=True, default='', max_length=32)),
                ('our_values', models.JSONField(blank=True, default=dict)),
                ('external_values', models.JSONField(blank=True, default=dict)),
                ('variances', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('match', 'Match'), ('variance', 'Variance'), ('external_only', 'External-only'), ('payroll_only', 'Missing from external')], db_index=True, default='match', max_length=32)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='payroll_engine.payrollcomparison')),
                ('payroll_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll_engine.payrollemployee')),
            ],
            options={
                'verbose_name': 'Payroll Comparison Row',
                'db_table': 'payroll_engine_comparison_row',
                'ordering': ('status', 'external_name'),
            },
        ),
        migrations.AddIndex(
            model_name='payrollcomparison',
            index=models.Index(fields=['run', '-created_at'], name='payroll_eng_run_id_b92150_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcomparisonrow',
            index=models.Index(fields=['comparison', 'status'], name='payroll_eng_compari_5d8985_idx'),
        ),
    ]
