# Generated by Django 4.2.16 on 2026-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0011_payrollrun_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrunupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payrollrunupload',
            name='unmatched',
            field=models.JSONField(blank=True, default=list, help_text='employee_no / names not found in this run'),
        ),
        migrations.AlterField(
            model_name='payrollrunupload',
            name='updated_fields',
            field=models.JSONField(blank=True, default=list, help_text='list of payslip field names that were written'),
        ),
    ]
