# Generated by Django 4.2.16 on 2026-07-08 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0012_add_total_worked_days_to_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='total_worked_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total worked days = (Hours ÷ Hours/Day) + Public Holidays + Annual Leave. Auto-calculated.', max_digits=8),
        ),
    ]
