# Generated by Django 5.0 on 2026-07-01 14:14
# Modified: replaced RenameIndex/RemoveIndex with conditional RunSQL
# so migration is safe on databases where these indexes may not exist (e.g. Railway production).

from django.db import migrations, models


class Migration(migrations.Migration):

    # Non-atomic: the NULL-backfill UPDATE queues PostgreSQL AFTER-triggers that
    # only fire at commit. A subsequent ALTER TABLE in the same transaction
    # raises ObjectInUse ("pending trigger events"). Committing per operation
    # avoids that while keeping each individual op transactional.
    atomic = False

    dependencies = [
        ('process_datasheet', '0018_pump_hydraulic_snapshot'),
    ]

    operations = [
        # ── Index operations: conditional SQL (safe when index does not exist) ──

        # DROP INDEX IF EXISTS supports missing indexes natively in PostgreSQL
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS pump_calculation_data_dest_flow_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS pump_calculation_data_total_pressure_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # RENAME INDEX: PostgreSQL has no ALTER INDEX IF EXISTS, use DO block instead
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pump_calculation_data_tag_no_project_no_idx') THEN
                        ALTER INDEX pump_calculation_data_tag_no_project_no_idx RENAME TO pump_calcul_tag_no_1ac76f_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pump_calculation_data_document_no_revision_idx') THEN
                        ALTER INDEX pump_calculation_data_document_no_revision_idx RENAME TO pump_calcul_documen_2fc886_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pump_calculation_data_status_updated_at_idx') THEN
                        ALTER INDEX pump_calculation_data_status_updated_at_idx RENAME TO pump_calcul_status_8d3b11_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ph_snap_user_proj_idx') THEN
                        ALTER INDEX ph_snap_user_proj_idx RENAME TO process_dat_user_id_bb3a97_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ph_snap_user_idx') THEN
                        ALTER INDEX ph_snap_user_idx RENAME TO process_dat_user_id_4fd13a_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ── Field operations: unchanged (standard Django operations) ──

        # Conditional column drops \u2014 safe if column already removed in production.
        # SeparateDatabaseAndState keeps Django's model state in sync while making
        # the actual SQL idempotent via DROP COLUMN IF EXISTS.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='pumpcalculationdata',
                    name='material_design',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE pump_calculation_data DROP COLUMN IF EXISTS material_design;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='pumpcalculationdata',
                    name='site_utility',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE pump_calculation_data DROP COLUMN IF EXISTS site_utility;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),

        # ── Backfill NULLs to '' on all CharField targets that will become NOT NULL ──
        # AlterField on CharField(blank=True) without null=True implies SET NOT NULL.
        # Production may hold NULL rows created before this migration; backfill first.
        # Uses information_schema check so it is safe if any column is absent.
        migrations.RunSQL(
            sql=r"""
                DO $$
                DECLARE
                    col text;
                    cols text[] := ARRAY[
                        'casing', 'company_name', 'driver_type', 'impeller',
                        'liquid_type', 'manufacturer', 'mechanical_seal', 'model',
                        'shaft', 'site', 'unit'
                    ];
                BEGIN
                    FOREACH col IN ARRAY cols LOOP
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'pump_calculation_data'
                              AND column_name = col
                        ) THEN
                            EXECUTE format(
                                'UPDATE pump_calculation_data SET %I = %L WHERE %I IS NULL',
                                col, '', col
                            );
                        END IF;
                    END LOOP;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='bearings',
            field=models.CharField(blank=True, help_text='Bearing type and material specification', max_length=200, null=True, verbose_name='Bearings Type'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='bhp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum brake horsepower in HP', max_digits=10, null=True, verbose_name='BHP (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='bhp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum brake horsepower in HP', max_digits=10, null=True, verbose_name='BHP (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='bhp_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal brake horsepower in HP', max_digits=10, null=True, verbose_name='BHP (Normal)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='casing',
            field=models.CharField(blank=True, help_text='Pump casing material specification', max_length=200, verbose_name='Casing Material'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or client name', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='density_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum density in kg/m³', max_digits=10, null=True, verbose_name='Density (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='density_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum density in kg/m³', max_digits=10, null=True, verbose_name='Density (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='destination_pressure',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Destination pressure', max_digits=10, null=True, verbose_name='Destination Pressure'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='differential_head_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum differential head in m', max_digits=10, null=True, verbose_name='Differential Head (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='differential_head_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum differential head in m', max_digits=10, null=True, verbose_name='Differential Head (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='differential_head_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal differential head in m', max_digits=10, null=True, verbose_name='Differential Head (Normal)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='differential_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum differential pressure in bar', max_digits=10, null=True, verbose_name='Differential Pressure (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='differential_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum differential pressure in bar', max_digits=10, null=True, verbose_name='Differential Pressure (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='differential_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal differential pressure in bar', max_digits=10, null=True, verbose_name='Differential Pressure (Normal)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum discharge pressure in bar', max_digits=10, null=True, verbose_name='Discharge Pressure (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum discharge pressure in bar', max_digits=10, null=True, verbose_name='Discharge Pressure (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal discharge pressure in bar', max_digits=10, null=True, verbose_name='Discharge Pressure (Normal)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='driver_type',
            field=models.CharField(blank=True, help_text='Type of driver (e.g., Electric Motor, Steam Turbine)', max_length=100, verbose_name='Driver Type'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='flow_rate_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum flow rate in m³/h', max_digits=10, null=True, verbose_name='Flow Rate (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='flow_rate_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum flow rate in m³/h', max_digits=10, null=True, verbose_name='Flow Rate (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='flow_rate_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal flow rate in m³/h', max_digits=10, null=True, verbose_name='Flow Rate (Normal)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='impeller',
            field=models.CharField(blank=True, help_text='Pump impeller material specification', max_length=200, verbose_name='Impeller Material'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='liquid_type',
            field=models.CharField(blank=True, help_text='Type of liquid being pumped', max_length=200, verbose_name='Liquid Type / Service'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Pump manufacturer name', max_length=200, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='mechanical_seal',
            field=models.CharField(blank=True, help_text='Mechanical seal type and specification', max_length=200, verbose_name='Mechanical Seal Type'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='model',
            field=models.CharField(blank=True, help_text='Pump model designation', max_length=200, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='motor_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Motor speed in RPM', max_digits=10, null=True, verbose_name='Motor Speed'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='npsh_available_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum NPSH available in m', max_digits=10, null=True, verbose_name='NPSH Available (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='npsh_available_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum NPSH available in m', max_digits=10, null=True, verbose_name='NPSH Available (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='npsh_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NPSH required by pump in m', max_digits=10, null=True, verbose_name='NPSH Required'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum pump efficiency in %', max_digits=5, null=True, verbose_name='Pump Efficiency (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum pump efficiency in %', max_digits=5, null=True, verbose_name='Pump Efficiency (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal pump efficiency in %', max_digits=5, null=True, verbose_name='Pump Efficiency (Normal)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='shaft',
            field=models.CharField(blank=True, help_text='Pump shaft material specification', max_length=200, verbose_name='Shaft Material'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='site',
            field=models.CharField(blank=True, help_text='Site or facility name', max_length=200, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='suction_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum suction pressure in bar', max_digits=10, null=True, verbose_name='Suction Pressure (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='suction_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum suction pressure in bar', max_digits=10, null=True, verbose_name='Suction Pressure (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='suction_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal suction pressure in bar', max_digits=10, null=True, verbose_name='Suction Pressure (Normal)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum operating temperature in °C', max_digits=10, null=True, verbose_name='Temperature (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum operating temperature in °C', max_digits=10, null=True, verbose_name='Temperature (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit or plant designation', max_length=100, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='vapor_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum vapor pressure in bar', max_digits=10, null=True, verbose_name='Vapor Pressure (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='vapor_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum vapor pressure in bar', max_digits=10, null=True, verbose_name='Vapor Pressure (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='viscosity_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum viscosity in cP', max_digits=10, null=True, verbose_name='Viscosity (Max)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='viscosity_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum viscosity in cP', max_digits=10, null=True, verbose_name='Viscosity (Min)'),
        ),
    ]
