# Generated by Django 4.2.16 on 2026-07-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique employee identifier', primary_key=True, serialize=False)),
                ('employee_number', models.CharField(db_index=True, help_text='Employee number from user_profiles table (primary legacy ID)', max_length=50, unique=True)),
                ('employee_code', models.CharField(db_index=True, help_text='Employee code from finance tables (salary, payroll)', max_length=50, unique=True)),
                ('emp_code', models.CharField(db_index=True, help_text='Employee code from timesheet/biometric system (truncated)', max_length=20, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Employee email (denormalized for performance)', max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_given_name', models.CharField(blank=True, help_text='Preferred first name for daily use', max_length=100)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo_file_path', models.CharField(blank=True, help_text='S3 key: media/employee_photos/{uuid}.{ext}', max_length=500)),
                ('photo_url', models.URLField(blank=True, help_text='Presigned S3 URL (auto-refreshed every 7 days)', max_length=1000)),
                ('photo_file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('photo_mime_type', models.CharField(blank=True, help_text='MIME type (image/jpeg, image/png)', max_length=100)),
                ('photo_uploaded_at', models.DateTimeField(blank=True, help_text='When photo was last uploaded', null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('division', models.CharField(blank=True, db_index=True, max_length=100)),
                ('business_unit', models.CharField(blank=True, max_length=100)),
                ('business_area', models.CharField(blank=True, max_length=100)),
                ('office', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, choices=[('RAD', 'Rejlers Abu Dhabi (RAD)'), ('RIN', 'Rejlers India (RIN)')], db_index=True, help_text='Operating branch/entity', max_length=20)),
                ('job_title_uae', models.CharField(blank=True, help_text='Job title for UAE operations', max_length=200)),
                ('job_title_finland', models.CharField(blank=True, help_text='Job title for Finland operations', max_length=200)),
                ('designation', models.CharField(blank=True, help_text='Official designation/position', max_length=100)),
                ('join_date', models.DateField(help_text='Date of joining the organization')),
                ('probation_end_date', models.DateField(blank=True, help_text='Expected end of probation period', null=True)),
                ('confirmation_date', models.DateField(blank=True, help_text='Date of employment confirmation', null=True)),
                ('exit_date', models.DateField(blank=True, help_text='Last working day (if exited)', null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('probation', 'On Probation'), ('notice_period', 'Notice Period'), ('exited', 'Exited'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Current employment status', max_length=20)),
                ('current_base_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Current base salary (denormalized for quick access)', max_digits=12, null=True)),
                ('currency', models.CharField(default='AED', help_text='Salary currency code (ISO 4217)', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number for salary transfer', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=34)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=11)),
                ('pan_number', models.CharField(blank=True, help_text='Permanent Account Number (India tax ID)', max_length=20)),
                ('uan_number', models.CharField(blank=True, help_text='Universal Account Number (India PF)', max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('employment_id', models.CharField(blank=True, db_index=True, help_text='Employment ID from external HRM system', max_length=50)),
                ('candidate_id', models.CharField(blank=True, help_text='Candidate ID from recruitment system', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='Active Directory account name', max_length=100)),
                ('is_test_person', models.BooleanField(default=False, help_text='Test/demo employee flag (exclude from reports)')),
                ('protected_identity', models.BooleanField(default=False, help_text='Protected identity flag (restrict access)')),
                ('not_signed', models.BooleanField(default=False, help_text='Contract not yet signed flag')),
                ('created_by', models.ForeignKey(help_text='User who created this employee record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_updated', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Direct reporting manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hr_core.employeemaster')),
                ('user', models.OneToOneField(help_text='Link to Django authentication user', on_delete=django.db.models.deletion.CASCADE, related_name='employee_master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Master Record',
                'verbose_name_plural': 'Employee Master Records',
                'db_table': 'hr_employee_master',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='hr_employee_email_5a2553_idx'), models.Index(fields=['employee_number'], name='hr_employee_employe_a58522_idx'), models.Index(fields=['employee_code'], name='hr_employee_employe_0bed2f_idx'), models.Index(fields=['emp_code'], name='hr_employee_emp_cod_e55f58_idx'), models.Index(fields=['employment_status', 'join_date'], name='hr_employee_employm_70e443_idx'), models.Index(fields=['department', 'division'], name='hr_employee_departm_318427_idx'), models.Index(fields=['branch', 'employment_status'], name='hr_employee_branch_4bd313_idx')],
            },
        ),
    ]
