# Generated by Django 5.0 on 2026-07-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='engineer_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Engineering expertise data: disciplines, skills, certifications, projects, availability', null=True),
        ),
    ]
