# Generated by Django 5.0 on 2026-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_podocument'),
    ]

    operations = [
        # Add PR requester name
        migrations.AddField(
            model_name='purchaseorder',
            name='pr_requester_name',
            field=models.CharField(max_length=200, blank=True, default='', help_text='Name of person who raised the PR'),
        ),
        
        # Add project fields
        migrations.AddField(
            model_name='purchaseorder',
            name='project_number',
            field=models.CharField(max_length=100, blank=True, default='', db_index=True, help_text='Project number or code'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project_manager',
            field=models.CharField(max_length=200, blank=True, default='', help_text='Project Manager name'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='budget',
            field=models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True, help_text='Project or PO budget'),
        ),
        
        # Add date fields
        migrations.AddField(
            model_name='purchaseorder',
            name='start_date',
            field=models.DateField(null=True, blank=True, help_text='Contract start date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='end_date',
            field=models.DateField(null=True, blank=True, help_text='Contract end date'),
        ),
        
        # Add delivery terms
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_terms',
            field=models.CharField(max_length=200, blank=True, default='', help_text='Incoterms (EXW, FOB, CIF, etc.)'),
        ),
        
        # Add payment milestones
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_milestones',
            field=models.JSONField(default=list, blank=True, help_text='Array of payment milestone objects [{description, percentage}]'),
        ),
    ]



