# Generated by Django 5.0 on 2026-06-24 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_add_comprehensive_po_fields'),
        ('finance', '__latest__'),  # Dependency on finance app for Invoice M2M
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ═══ Create CostCenter Master Table ═══
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='CC-XXX format', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, help_text='Process, Piping, Electrical, etc.', max_length=100)),
                ('division', models.CharField(blank=True, help_text='Engineering, Finance, QHSE, etc.', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['code'],
            },
        ),
        
        # ═══ Create Project Master Table ═══
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(db_index=True, help_text='Unique project identifier', max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=300)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_reference', models.CharField(blank=True, help_text='Client PO/Contract number', max_length=100)),
                ('project_type', models.CharField(choices=[
                    ('engineering', 'Engineering Services'),
                    ('construction', 'Construction'),
                    ('maintenance', 'Maintenance & Operations'),
                    ('pmc', 'Project Management Consultancy'),
                    ('feasibility', 'Feasibility Study'),
                    ('feed', 'Front-End Engineering Design (FEED)'),
                    ('detailed_design', 'Detailed Engineering'),
                    ('commissioning', 'Commissioning & Startup'),
                    ('shutdown', 'Shutdown & Turnaround'),
                    ('brownfield', 'Brownfield Modification'),
                    ('greenfield', 'Greenfield Development'),
                    ('internal', 'Internal Project'),
                ], default='engineering', max_length=30)),
                ('status', models.CharField(choices=[
                    ('planning', 'Planning'),
                    ('active', 'Active'),
                    ('on_hold', 'On Hold'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                    ('archived', 'Archived'),
                ], db_index=True, default='planning', max_length=20)),
                ('project_manager_name', models.CharField(blank=True, help_text='Fallback if PM not in system', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scope_of_work', models.TextField(blank=True)),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of expected deliverables')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('site_location', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('contract_currency', models.CharField(default='AED', max_length=10)),
                ('payment_terms', models.TextField(blank=True)),
                ('progress_percentage', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5,
                    validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]
                )),
                ('health_status', models.CharField(choices=[
                    ('green', 'On Track'),
                    ('yellow', 'At Risk'),
                    ('red', 'Critical'),
                ], default='green', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Searchable tags')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_billable', models.BooleanField(default=True, help_text='Client-billable project')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal R&D/overhead project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        
        # ═══ Create Budget Master Table ═══
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[
                    ('engineering', 'Engineering Services'),
                    ('procurement', 'Procurement & Materials'),
                    ('equipment', 'Equipment & Machinery'),
                    ('construction', 'Construction & Installation'),
                    ('manpower', 'Manpower & Labor'),
                    ('travel', 'Travel & Accommodation'),
                    ('testing', 'Testing & Commissioning'),
                    ('certification', 'Certification & Inspection'),
                    ('software', 'Software & Licenses'),
                    ('training', 'Training & Development'),
                    ('consultancy', 'Consultancy Services'),
                    ('contingency', 'Contingency Reserve'),
                    ('overhead', 'Overhead & Admin'),
                    ('other', 'Other Expenses'),
                ], max_length=30)),
                ('sub_category', models.CharField(blank=True, help_text='Detailed breakdown', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('allocated_amount', models.DecimalField(
                    decimal_places=2, max_digits=18,
                    validators=[django.core.validators.MinValueValidator(0)]
                )),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['project', 'category'],
            },
        ),
        
        # ═══ Add Foreign Keys to PurchaseOrder ═══
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='purchase_orders',
                to='procurement.project',
                help_text='Link to master project registry'
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='budget_allocation',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='purchase_orders',
                to='procurement.budget',
                help_text='Link to specific budget line item'
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('not_invoiced', 'Not Invoiced'),
                    ('partially_invoiced', 'Partially Invoiced'),
                    ('fully_invoiced', 'Fully Invoiced'),
                    ('over_invoiced', 'Over Invoiced'),
                ],
                default='not_invoiced',
                help_text='Invoice reconciliation status'
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_invoiced_amount',
            field=models.DecimalField(
                max_digits=15, decimal_places=2, default=0,
                help_text='Sum of all related invoice amounts'
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='related_invoices',
            field=models.ManyToManyField(
                blank=True,
                related_name='purchase_orders',
                to='finance.invoice',
                help_text='Vendor invoices against this PO'
            ),
        ),
        
        # ═══ Add Foreign Keys to Other Models ═══
        # User FKs for CostCenter
        migrations.AddField(
            model_name='costcenter',
            name='manager',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_cost_centers',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='procurement.costcenter'
            ),
        ),
        
        # User FKs for Project
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_projects',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_engineer',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='led_projects',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(
                blank=True,
                related_name='project_memberships',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_center',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='procurement.costcenter'
            ),
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='budgets',
                to='procurement.project'
            ),
        ),
        migrations.AddField(
            model_name='budget',
            name='cost_center',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='procurement.costcenter'
            ),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_budgets',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # ═══ Add Indexes ═══
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['code', 'is_active'], name='procurement_costcenter_idx1'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['department', 'division'], name='procurement_costcenter_idx2'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_number'], name='procurement_project_idx1'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_active'], name='procurement_project_idx2'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_name', 'project_type'], name='procurement_project_idx3'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'planned_end_date'], name='procurement_project_idx4'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['project', 'category'], name='procurement_budget_idx1'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fiscal_year', 'is_approved'], name='procurement_budget_idx2'),
        ),
    ]
