# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_add_master_database_tables'),
    ]

    operations = [
        # Conditional index renames — safe when index does not exist in production
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_budget_idx1') THEN ALTER INDEX procurement_budget_idx1 RENAME TO procurement_project_cf65fc_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_budget_idx2') THEN ALTER INDEX procurement_budget_idx2 RENAME TO procurement_fiscal__0de50e_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_costcenter_idx1') THEN ALTER INDEX procurement_costcenter_idx1 RENAME TO procurement_code_f170f4_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_costcenter_idx2') THEN ALTER INDEX procurement_costcenter_idx2 RENAME TO procurement_departm_ea9b87_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx1') THEN ALTER INDEX procurement_project_idx1 RENAME TO procurement_project_3cb8c1_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx2') THEN ALTER INDEX procurement_project_idx2 RENAME TO procurement_status_5adfc7_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx3') THEN ALTER INDEX procurement_project_idx3 RENAME TO procurement_client__88c69c_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx4') THEN ALTER INDEX procurement_project_idx4 RENAME TO procurement_start_d_19f6a3_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g., Net 30, 50% advance / 50% completion', max_length=300),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allocated budget for this PO (deprecated, use budget_allocation FK)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_terms',
            field=models.CharField(blank=True, help_text='e.g., FOB, CIF, DAP, DDP', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='end_date',
            field=models.DateField(blank=True, help_text='Service/Project end date', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_milestones',
            field=models.JSONField(blank=True, default=list, help_text='Payment schedule milestones'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='pr_requester_name',
            field=models.CharField(blank=True, help_text='Name of person who requested the PR', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='project_manager',
            field=models.CharField(blank=True, help_text='Project Manager name (soft-coded)', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='project_number',
            field=models.CharField(blank=True, db_index=True, help_text='Project code (for AI extraction / legacy compatibility)', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='start_date',
            field=models.DateField(blank=True, help_text='Service/Project start date', null=True),
        ),
    ]
