# Generated by Django 5.0 on 2026-06-23 13:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_salary_slip_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='pdf_s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for the uploaded PDF (payroll/slips/YYYY/MM/slip.pdf)', max_length=600),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='pdf_s3_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PayrollSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='When True, the Celery Beat task will auto-generate payroll on schedule.')),
                ('day_of_month', models.IntegerField(default=1, help_text='Day of month on which the task fires (1-28). Default = 1st.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('days_after_month_end', models.IntegerField(default=0, help_text='How many days after month-end to wait before generating. 0 = generate immediately.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('auto_send_emails', models.BooleanField(default=False, help_text='When True, emails are queued for all approved slips after generation.')),
                ('notify_emails', models.TextField(blank=True, help_text='Comma-separated email addresses to notify on success / failure.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('last_run_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_schedule_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Auto-Schedule',
                'verbose_name_plural': 'Payroll Auto-Schedule',
                'db_table': 'finance_payroll_schedule',
            },
        ),
    ]
