# Generated by Django 5.0 on 2026-07-01 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_payroll_schedule_and_s3_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('draft', 'Draft'), ('hr_review', 'HR Review'), ('accounting_review', 'Accounting Review'), ('finance_review', 'Finance Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released to Employees')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('accounting_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_comments', models.TextField(blank=True)),
                ('finance_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finance_comments', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_stage', models.CharField(blank=True, max_length=30)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_reviewed_payrolls', to=settings.AUTH_USER_MODEL)),
                ('finance_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_payrolls', to=settings.AUTH_USER_MODEL)),
                ('hr_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_payrolls', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='finance.payrollrun')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payroll_workflows', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payroll_workflows', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payroll_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Workflow',
                'verbose_name_plural': 'Payroll Workflows',
                'db_table': 'finance_payroll_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='finance.payrollworkflow')),
            ],
            options={
                'verbose_name': 'Workflow Notification Log',
                'verbose_name_plural': 'Workflow Notification Logs',
                'db_table': 'finance_workflow_notification_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollworkflow',
            index=models.Index(fields=['payroll_run'], name='finance_pay_payroll_2e44bb_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollworkflow',
            index=models.Index(fields=['current_stage'], name='finance_pay_current_f666ab_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollworkflow',
            index=models.Index(fields=['submitted_at'], name='finance_pay_submitt_79c6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotificationlog',
            index=models.Index(fields=['workflow'], name='finance_wor_workflo_831dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotificationlog',
            index=models.Index(fields=['notification_type'], name='finance_wor_notific_3cd037_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotificationlog',
            index=models.Index(fields=['delivery_status'], name='finance_wor_deliver_f957e4_idx'),
        ),
    ]
