# Generated by Django 5.0 on 2026-07-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0008_pidequipmenttype_pidequipmentitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(editable=False, help_text='Auto-generated unique project ID', max_length=50, unique=True)),
                ('project_name', models.CharField(help_text='User-defined project name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional project description', null=True)),
                ('organization', models.CharField(blank=True, help_text='Organization name for RBAC S3 path', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pid_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='pidequipmentitem',
            name='pid_equip_item_upload_tag_uniq',
        ),
        migrations.RenameIndex(
            model_name='pidequipmentitem',
            new_name='pid_equipme_drawing_897b8a_idx',
            old_name='pid_equip_item_drw_tag_idx',
        ),
        migrations.RenameIndex(
            model_name='pidequipmentitem',
            new_name='pid_equipme_upload__6df543_idx',
            old_name='pid_equip_item_upload_idx',
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='area',
            field=models.CharField(blank=True, help_text='Area code (2 digits)', max_length=2),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='doc_code',
            field=models.CharField(blank=True, help_text='Document code (2 digits)', max_length=2),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='p_area',
            field=models.CharField(blank=True, help_text='P/Area code (2 digits)', max_length=2),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='rev',
            field=models.CharField(blank=True, help_text='Revision (1 digit)', max_length=1),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number (4 digits)', max_length=4),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='sheet_number',
            field=models.CharField(blank=True, default='1', help_text='Sheet number', max_length=1),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='total_sheets',
            field=models.CharField(blank=True, default='1', help_text='Total sheets', max_length=1),
        ),
        migrations.AddField(
            model_name='pidissue',
            name='location_on_drawing',
            field=models.JSONField(blank=True, help_text='Location information: zone, drawing_section, proximity_description, visual_cues', null=True),
        ),
        migrations.AlterField(
            model_name='pidequipmentitem',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted process parameters: oper_pressure, oper_temperature, design_pressure_max, design_temp_max, moc, insulation, dimension_length, dimension_diameter, motor_rating, etc.'),
        ),
        migrations.AlterField(
            model_name='pidequipmentitem',
            name='drawing_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Drawing / DWG NO extracted from title block', max_length=120),
        ),
        migrations.AlterField(
            model_name='pidequipmentitem',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Classified equipment type (FK to designation code table)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='pid_analysis.pidequipmenttype'),
        ),
        migrations.AlterField(
            model_name='pidequipmentitem',
            name='extraction_mode',
            field=models.CharField(blank=True, help_text='pid_drawing | equipment_register', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='pidequipmentitem',
            unique_together={('upload_id', 'tag')},
        ),
        migrations.AddField(
            model_name='pidproject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated P&ID project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid_drawings', to='pid_analysis.pidproject'),
        ),
        migrations.AddIndex(
            model_name='pidproject',
            index=models.Index(fields=['project_id'], name='pid_project_project_209c56_idx'),
        ),
        migrations.AddIndex(
            model_name='pidproject',
            index=models.Index(fields=['created_by', '-created_at'], name='pid_project_created_09046f_idx'),
        ),
        migrations.AddIndex(
            model_name='pidproject',
            index=models.Index(fields=['organization'], name='pid_project_organiz_a8e179_idx'),
        ),
    ]
