# Generated by Django 5.0 on 2026-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('employee_code', models.CharField(db_index=True, max_length=64)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('employee_email', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], db_index=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['employee_code', '-event_time'], name='timesheet_t_employe_c7f751_idx'), models.Index(fields=['-event_time', 'event_type'], name='timesheet_t_event_t_3f0eef_idx')],
            },
        ),
    ]
