# Generated by Django 5.0 on 2026-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricUserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('card1', models.CharField(blank=True, default='', max_length=64)),
                ('card2', models.CharField(blank=True, default='', max_length=64)),
                ('office_email', models.CharField(blank=True, default='', max_length=255)),
                ('personal_email', models.CharField(blank=True, default='', max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
    ]
