# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_normalize_employee_identity'),
    ]

    operations = [
        # Conditional constraint / index drops \u2014 safe when not present in production.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='dailyattendancesummary',
                    name='ts_daily_sum_unique_code_date',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE timesheet_dailyattendancesummary DROP CONSTRAINT IF EXISTS ts_daily_sum_unique_code_date;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='timesheetevent',
                    name='ts_event_emp_name_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS ts_event_emp_name_idx;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='timesheetevent',
                    name='ts_event_emp_email_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS ts_event_emp_email_idx;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='effective_hours',
            field=models.FloatField(db_index=True, default=0.0, help_text='Hours field consumed by payroll and attendance reports. Equals paired_hours when mode=paired, else elapsed_hours.'),
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='paired_hours',
            field=models.FloatField(default=0.0, help_text='Sum of completed IN→OUT pair durations (hours). Only changes when a matching OUT punch arrives.'),
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='paired_segments',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of matched IN→OUT pairs.'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancesummary',
            unique_together={('employee_code', 'date')},
        ),
    ]
