# Generated by Django 5.0 on 2026-07-01 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMiningProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('wrench_project_number', models.CharField(blank=True, help_text='Wrench project/order number', max_length=100)),
                ('wrench_project_name', models.CharField(blank=True, help_text='Wrench project name', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configuring', 'Configuring Pipeline'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('master_file_path', models.CharField(blank=True, help_text='S3 path to generated master file', max_length=500)),
                ('master_file_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('parquet', 'Parquet')], default='excel', max_length=50)),
                ('total_documents', models.IntegerField(default=0)),
                ('total_rows_processed', models.IntegerField(default=0)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_mining_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_mining_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataMiningDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wrench_doc_number', models.CharField(help_text='Wrench document number', max_length=255)),
                ('wrench_doc_title', models.CharField(blank=True, max_length=500)),
                ('wrench_doc_revision', models.CharField(blank=True, max_length=50)),
                ('wrench_transmittal_id', models.CharField(blank=True, max_length=100)),
                ('file_path', models.CharField(blank=True, help_text='S3 path to downloaded document', max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('word', 'Word'), ('dwg', 'AutoCAD'), ('other', 'Other')], default='pdf', max_length=50)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('extracted_data', models.JSONField(blank=True, help_text='Extracted tabular data from document', null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('sequence_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='data_mining.dataminingproject')),
            ],
            options={
                'db_table': 'data_mining_documents',
                'ordering': ['project', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='TransformationPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Pipeline', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('canvas_config', models.JSONField(default=dict, help_text='Visual layout: node positions, connections')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='data_mining.dataminingproject')),
            ],
            options={
                'db_table': 'transformation_pipelines',
            },
        ),
        migrations.CreateModel(
            name='TransformationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(help_text='User-friendly step name', max_length=255)),
                ('operation_type', models.CharField(choices=[('join', 'Join - Merge datasets by common key'), ('filter', 'Filter - Remove unwanted rows'), ('aggregate', 'Aggregate - Sum, avg, count, min, max'), ('clean', 'Clean - Remove duplicates, handle nulls'), ('derive', 'Derive - Create calculated fields'), ('pivot', 'Pivot - Convert rows to columns'), ('unpivot', 'Unpivot - Convert columns to rows'), ('union', 'Union - Stack datasets vertically'), ('rename', 'Rename - Rename columns'), ('select', 'Select - Choose specific columns'), ('sort', 'Sort - Order by columns'), ('sample', 'Sample - Take random subset')], help_text='Type of transformation', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='\n        Soft-coded configuration per operation type:\n        \n        JOIN:\n            {\n                "join_type": "inner|left|right|outer",\n                "left_input": "step_id or document_id",\n                "right_input": "step_id or document_id",\n                "left_key": "column_name",\n                "right_key": "column_name"\n            }\n        \n        FILTER:\n            {\n                "conditions": [\n                    {"column": "status", "operator": "equals", "value": "Active"},\n                    {"column": "amount", "operator": "greater_than", "value": 1000}\n                ],\n                "logic": "and|or"\n            }\n        \n        AGGREGATE:\n            {\n                "group_by": ["project", "category"],\n                "aggregations": [\n                    {"column": "amount", "function": "sum", "output_name": "total_amount"},\n                    {"column": "quantity", "function": "avg", "output_name": "avg_quantity"}\n                ]\n            }\n        \n        CLEAN:\n            {\n                "remove_duplicates": true,\n                "drop_null_rows": ["column1", "column2"],\n                "fill_null_value": {"column3": 0, "column4": "N/A"}\n            }\n        \n        DERIVE:\n            {\n                "new_columns": [\n                    {\n                        "name": "total_price",\n                        "expression": "quantity * unit_price",\n                        "data_type": "float"\n                    }\n                ]\n            }\n        \n        RENAME:\n            {\n                "column_mapping": {\n                    "old_name1": "new_name1",\n                    "old_name2": "new_name2"\n                }\n            }\n        \n        SELECT:\n            {\n                "columns": ["col1", "col2", "col3"]\n            }\n        \n        UNION:\n            {\n                "inputs": ["step_id1", "step_id2"],\n                "align_columns": true\n            }\n        ')),
                ('input_source', models.CharField(blank=True, help_text='UUID of previous step or document', max_length=255)),
                ('output_preview', models.JSONField(blank=True, help_text='Sample rows after transformation (first 100 rows)', null=True)),
                ('output_row_count', models.IntegerField(default=0)),
                ('output_column_count', models.IntegerField(default=0)),
                ('sequence_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='data_mining.transformationpipeline')),
            ],
            options={
                'db_table': 'transformation_steps',
                'ordering': ['pipeline', 'sequence_order'],
            },
        ),
    ]
