# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'invoice_tra_account_dab1bb_idx') THEN
                        ALTER INDEX invoice_tra_account_dab1bb_idx RENAME TO invoice_tra_account_55b104_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'invoice_tra_rad_pro_71f8b9_idx') THEN
                        ALTER INDEX invoice_tra_rad_pro_71f8b9_idx RENAME TO invoice_tra_rad_pro_21a969_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
