# Generated by Django 5.0 on 2026-06-25 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Site name (e.g., "ADNOC Tower 2")', max_length=200)),
                ('client_name', models.CharField(db_index=True, help_text='Client/Company name', max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Abu Dhabi', max_length=100)),
                ('country', models.CharField(default='UAE', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude in decimal degrees (e.g., 24.4539)', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude in decimal degrees (e.g., 54.3773)', max_digits=10, null=True)),
                ('geofence_radius', models.IntegerField(default=100, help_text='Radius in meters for auto check-in geofence')),
                ('require_photo', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Site',
                'verbose_name_plural': 'Client Sites',
                'db_table': 'site_visit_client_site',
                'ordering': ['client_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('employee_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.TextField(help_text='Reason for site visit')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_site_visit_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visit_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_requests', to='site_visits.clientsite')),
            ],
            options={
                'verbose_name': 'Site Visit Request',
                'verbose_name_plural': 'Site Visit Requests',
                'db_table': 'site_visit_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(db_index=True, max_length=30)),
                ('employee_name', models.CharField(max_length=255)),
                ('check_in_time', models.DateTimeField(db_index=True)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('check_in_method', models.CharField(choices=[('GPS', 'GPS Location'), ('QR_CODE', 'QR Code Scan'), ('MANUAL', 'Manual Entry'), ('GEOFENCE', 'Auto Geofence')], default='GPS', max_length=20)),
                ('check_in_photo', models.FileField(blank=True, null=True, upload_to='site_visits/check_in/')),
                ('check_out_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_accuracy', models.FloatField(blank=True, null=True)),
                ('check_out_method', models.CharField(blank=True, choices=[('GPS', 'GPS Location'), ('QR_CODE', 'QR Code Scan'), ('MANUAL', 'Manual Entry'), ('GEOFENCE', 'Auto Geofence')], max_length=20, null=True)),
                ('check_out_photo', models.FileField(blank=True, null=True, upload_to='site_visits/check_out/')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total hours on-site', max_digits=6, null=True)),
                ('geofence_valid', models.BooleanField(default=False, help_text='Check-in within geofence radius')),
                ('gps_accuracy_ok', models.BooleanField(default=True, help_text='GPS accuracy meets threshold')),
                ('employee_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('offline_created', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_check_ins', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='site_visits.clientsite')),
                ('visit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='site_visits.sitevisitrequest')),
            ],
            options={
                'verbose_name': 'Site Visit Check-In',
                'verbose_name_plural': 'Site Visit Check-Ins',
                'db_table': 'site_visit_check_in',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.AddIndex(
            model_name='clientsite',
            index=models.Index(fields=['client_name', 'is_active'], name='site_visit__client__8d4e85_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsite',
            index=models.Index(fields=['is_active', 'created_at'], name='site_visit__is_acti_8a90f0_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitrequest',
            index=models.Index(fields=['employee_code', 'start_date', 'end_date'], name='site_visit__employe_9e4e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitrequest',
            index=models.Index(fields=['status', 'start_date'], name='site_visit__status_4c1e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitrequest',
            index=models.Index(fields=['site', 'status'], name='site_visit__site_id_3f8e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitcheckin',
            index=models.Index(fields=['employee_code', 'check_in_time'], name='site_visit__employe_7a9e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitcheckin',
            index=models.Index(fields=['site', 'check_in_time'], name='site_visit__site_id_2c7f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitcheckin',
            index=models.Index(fields=['check_in_time', 'check_out_time'], name='site_visit__check_i_5e8b9c_idx'),
        ),
    ]

