# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_visits', '0001_init_site_visit_tracking'),
    ]

    operations = [
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__client__8d4e85_idx') THEN ALTER INDEX site_visit__client__8d4e85_idx RENAME TO site_visit__client__eb6632_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__is_acti_8a90f0_idx') THEN ALTER INDEX site_visit__is_acti_8a90f0_idx RENAME TO site_visit__is_acti_685e85_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__employe_7a9e3b_idx') THEN ALTER INDEX site_visit__employe_7a9e3b_idx RENAME TO site_visit__employe_a42731_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__site_id_2c7f4a_idx') THEN ALTER INDEX site_visit__site_id_2c7f4a_idx RENAME TO site_visit__site_id_1bc7ef_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__check_i_5e8b9c_idx') THEN ALTER INDEX site_visit__check_i_5e8b9c_idx RENAME TO site_visit__check_i_b3b837_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__employe_9e4e8c_idx') THEN ALTER INDEX site_visit__employe_9e4e8c_idx RENAME TO site_visit__employe_9398a8_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__status_4c1e9f_idx') THEN ALTER INDEX site_visit__status_4c1e9f_idx RENAME TO site_visit__status_ff8f81_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'site_visit__site_id_3f8e1d_idx') THEN ALTER INDEX site_visit__site_id_3f8e1d_idx RENAME TO site_visit__site_id_c1fcf0_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
    ]
