# Generated by Django 5.0 on 2026-05-15 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_customization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbookCellOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workbook', models.CharField(choices=[('spec', 'SPEC'), ('cat', 'CAT')], db_index=True, max_length=8)),
                ('sheet_name', models.CharField(db_index=True, max_length=128)),
                ('row_key', models.CharField(db_index=True, max_length=256)),
                ('column_name', models.CharField(max_length=128)),
                ('value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='paperspecdocument',
            new_name='spec_custom_sha256__ce399b_idx',
            old_name='spec_cust_pa_sha256__idx',
        ),
        migrations.RenameIndex(
            model_name='paperspecdocument',
            new_name='spec_custom_created_e3e559_idx',
            old_name='spec_cust_pa_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paperspecextractionjob',
            new_name='spec_custom_status_cc7b14_idx',
            old_name='spec_cust_jo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paperspecextractionjob',
            new_name='spec_custom_celery__66a838_idx',
            old_name='spec_cust_jo_celery_idx',
        ),
        migrations.RenameIndex(
            model_name='pipingclass',
            new_name='spec_custom_job_id_752a66_idx',
            old_name='spec_cust_pc_job_code_idx',
        ),
        migrations.RenameIndex(
            model_name='pipingclasscomponent',
            new_name='spec_custom_piping__35b7ee_idx',
            old_name='spec_cust_pcc_pc_type_idx',
        ),
        migrations.AddField(
            model_name='workbookcelloverride',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_workbook_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workbookcelloverride',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbook_overrides', to='spec_customization.paperspecextractionjob'),
        ),
        migrations.AddIndex(
            model_name='workbookcelloverride',
            index=models.Index(fields=['job', 'workbook', 'sheet_name'], name='spec_custom_job_id_3d5c40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workbookcelloverride',
            unique_together={('job', 'workbook', 'sheet_name', 'row_key', 'column_name')},
        ),
    ]
