# Generated by Django 5.0 on 2026-05-21 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_customization', '0002_workbookcelloverride_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecProject',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('client', models.CharField(blank=True, max_length=128)),
                ('plant', models.CharField(blank=True, max_length=128)),
                ('discipline', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_customization_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spec Customization Project',
                'verbose_name_plural': 'Spec Customization Projects',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='spec_custom_status_9f405f_idx'), models.Index(fields=['created_by', '-updated_at'], name='spec_custom_created_061335_idx')],
            },
        ),
    ]
