# Generated by Django 4.2.16 on 2026-07-06 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spec_customization', '0003_specproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingWorkbookSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(blank=True, default='', max_length=128)),
                ('match_file', models.FileField(blank=True, help_text='Match.xlsx — PDF component name to Excel catalog name mapping', null=True, upload_to='spec_customization/matching/%Y/%m/')),
                ('spec_file', models.FileField(blank=True, help_text='SPEC.xlsx — Specification rules (25 sheets)', null=True, upload_to='spec_customization/matching/%Y/%m/')),
                ('cat_file', models.FileField(blank=True, help_text='CAT.xlsx — Component catalog (23 sheets)', null=True, upload_to='spec_customization/matching/%Y/%m/')),
                ('match_file_name', models.CharField(blank=True, default='', max_length=256)),
                ('spec_file_name', models.CharField(blank=True, default='', max_length=256)),
                ('cat_file_name', models.CharField(blank=True, default='', max_length=256)),
                ('is_parsed', models.BooleanField(db_index=True, default=False)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('rules_count', models.IntegerField(default=0, help_text='Number of MatchingRules extracted from Match.xlsx')),
                ('spec_sheets_count', models.IntegerField(default=0)),
                ('cat_sheets_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_workbook_sets', to='spec_customization.specproject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_matching_workbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matching Workbook Set',
                'verbose_name_plural': 'Matching Workbook Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_component_name', models.CharField(db_index=True, help_text='Component name as it appears in PDF (e.g., "GATE VALVE", "90 DEGREE ELBOW")', max_length=256)),
                ('catalog_component_name', models.CharField(db_index=True, help_text='Corresponding name in Excel CAT workbook (e.g., "Gate Valve", "90 Degree Direction Change")', max_length=256)),
                ('cat_sheet_name', models.CharField(blank=True, help_text='CAT.xlsx sheet name (spaces removed, e.g., "GateValve", "90DegElbow")', max_length=128)),
                ('matching_config', models.JSONField(blank=True, default=dict, help_text='Optional: size/rating/material overrides for this component type')),
                ('row_number', models.IntegerField(default=0, help_text='Row number in Match.xlsx for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workbook_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='spec_customization.matchingworkbookset')),
            ],
            options={
                'verbose_name': 'Matching Rule',
                'verbose_name_plural': 'Matching Rules',
                'ordering': ['pdf_component_name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentMatchingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_component_name', models.CharField(db_index=True, max_length=256)),
                ('nominal_size', models.CharField(blank=True, help_text='e.g., "2", "4", "DN50"', max_length=32)),
                ('pressure_rating', models.CharField(blank=True, help_text='e.g., "150#", "300#", "PN16"', max_length=32)),
                ('material_grade', models.CharField(blank=True, help_text='e.g., "A105", "316SS"', max_length=64)),
                ('matched_commodity_code', models.CharField(blank=True, help_text='IndustryCommodityCode from CAT.xlsx (e.g., "DHGA01CMA1")', max_length=128)),
                ('matched_description', models.TextField(blank=True, default='')),
                ('match_score', models.FloatField(default=0.0, help_text='Confidence score 0-1')),
                ('match_method', models.CharField(blank=True, help_text='e.g., "exact", "fuzzy", "rule-based"', max_length=64)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workbook_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='spec_customization.matchingworkbookset')),
            ],
            options={
                'verbose_name': 'Component Matching Result',
                'verbose_name_plural': 'Component Matching Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='matchingworkbookset',
            index=models.Index(fields=['project', 'is_active'], name='spec_custom_project_d7e611_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingworkbookset',
            index=models.Index(fields=['-created_at'], name='spec_custom_created_e46ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingrule',
            index=models.Index(fields=['workbook_set', 'pdf_component_name'], name='spec_custom_workboo_a1114e_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingrule',
            index=models.Index(fields=['catalog_component_name'], name='spec_custom_catalog_3671f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingrule',
            constraint=models.UniqueConstraint(fields=('workbook_set', 'pdf_component_name'), name='unique_rule_per_workbook_set'),
        ),
        migrations.AddIndex(
            model_name='componentmatchingresult',
            index=models.Index(fields=['workbook_set', 'pdf_component_name'], name='spec_custom_workboo_009fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='componentmatchingresult',
            index=models.Index(fields=['-created_at'], name='spec_custom_created_9d3335_idx'),
        ),
    ]
