# Generated by Django 5.0 on 2026-07-01 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDisciplineRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_type', models.CharField(choices=[('complementary_doc', 'Complementary Document Needed'), ('interface_check', 'Interface Check Required'), ('specification_update', 'Specification Update Needed'), ('review_request', 'Review Request'), ('dependency_alert', 'Dependency Alert')], max_length=50)),
                ('recommendation_text', models.TextField()),
                ('suggested_document_types', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('ai_confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_cross_discipline_recommendations',
            },
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('references', 'References'), ('supersedes', 'Supersedes'), ('complements', 'Complements'), ('depends_on', 'Depends On'), ('similar_to', 'Similar To'), ('part_of', 'Part Of')], max_length=20)),
                ('confidence_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_by_ai', models.BooleanField(default=False)),
                ('verified_by_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_document_relationships',
            },
        ),
        migrations.CreateModel(
            name='ProjectCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(default='engineering', max_length=50)),
                ('project_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('archived', 'Archived')], default='active', max_length=20)),
                ('total_documents', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('discipline_count', models.IntegerField(default=0)),
                ('s3_root_path', models.CharField(max_length=500)),
                ('folder_structure', models.JSONField(blank=True, default=dict)),
                ('auto_organize_enabled', models.BooleanField(default=True)),
                ('ai_classification_enabled', models.BooleanField(default=True)),
                ('cross_discipline_recommendations', models.BooleanField(default=True)),
                ('last_document_upload', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_project_collections',
            },
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discipline_name', models.CharField(max_length=50)),
                ('discipline_type', models.CharField(choices=[('process', 'Process Engineering'), ('mechanical', 'Mechanical Engineering'), ('electrical', 'Electrical Engineering'), ('instrumentation', 'Instrumentation & Control'), ('civil', 'Civil & Structural'), ('piping', 'Piping Engineering'), ('safety', 'Safety & Risk'), ('environmental', 'Environmental'), ('general', 'General Documents')], default='general', max_length=20)),
                ('document_count', models.IntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('s3_discipline_path', models.CharField(max_length=600)),
                ('document_types', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'core_project_disciplines',
            },
        ),
        migrations.CreateModel(
            name='SmartProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('document_subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('document_category', models.CharField(choices=[('drawing', 'Technical Drawing'), ('specification', 'Specification Document'), ('datasheet', 'Equipment Datasheet'), ('calculation', 'Engineering Calculation'), ('report', 'Technical Report'), ('procedure', 'Operating Procedure'), ('manual', 'Equipment Manual'), ('certificate', 'Certificate/Approval'), ('other', 'Other Document')], default='other', max_length=20)),
                ('s3_key', models.CharField(max_length=1000)),
                ('original_s3_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_size', models.BigIntegerField()),
                ('file_extension', models.CharField(max_length=10)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ai_classification_confidence', models.FloatField(default=0.0, help_text='AI confidence in document classification', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_extracted_metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superseded', models.BooleanField(default=False)),
                ('revision', models.CharField(default='A', max_length=20)),
                ('revision_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_smart_project_documents',
            },
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'core_enquir_created_idx') THEN
                        ALTER INDEX core_enquir_created_idx RENAME TO core_enquir_created_8e0bcb_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'core_enquir_status_idx') THEN
                        ALTER INDEX core_enquir_status_idx RENAME TO core_enquir_status_2f25e5_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='crossdisciplinerecommendation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cross_discipline_recs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectcollection',
            index=models.Index(fields=['project_code'], name='core_projec_project_d0f528_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollection',
            index=models.Index(fields=['project_status', 'updated_at'], name='core_projec_project_f3dd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollection',
            index=models.Index(fields=['last_document_upload'], name='core_projec_last_do_12dfdb_idx'),
        ),
        migrations.AddField(
            model_name='crossdisciplinerecommendation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_discipline_recs', to='core.projectcollection'),
        ),
        migrations.AddField(
            model_name='projectdiscipline',
            name='lead_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_disciplines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdiscipline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='core.projectcollection'),
        ),
        migrations.AddField(
            model_name='crossdisciplinerecommendation',
            name='source_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='core.projectdiscipline'),
        ),
        migrations.AddField(
            model_name='crossdisciplinerecommendation',
            name='target_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to='core.projectdiscipline'),
        ),
        migrations.AddField(
            model_name='smartprojectdocument',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.projectdiscipline'),
        ),
        migrations.AddField(
            model_name='smartprojectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.projectcollection'),
        ),
        migrations.AddField(
            model_name='smartprojectdocument',
            name='related_documents',
            field=models.ManyToManyField(blank=True, help_text='Related documents in the project', through='core.DocumentRelationship', to='core.smartprojectdocument'),
        ),
        migrations.AddField(
            model_name='smartprojectdocument',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.smartprojectdocument'),
        ),
        migrations.AddField(
            model_name='smartprojectdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrelationship',
            name='from_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.smartprojectdocument'),
        ),
        migrations.AddField(
            model_name='documentrelationship',
            name='to_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.smartprojectdocument'),
        ),
        migrations.AddField(
            model_name='crossdisciplinerecommendation',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers_recommendations', to='core.smartprojectdocument'),
        ),
        migrations.AddIndex(
            model_name='projectdiscipline',
            index=models.Index(fields=['project', 'discipline_type'], name='core_projec_project_b35440_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdiscipline',
            index=models.Index(fields=['discipline_type', 'document_count'], name='core_projec_discipl_a1658d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdiscipline',
            unique_together={('project', 'discipline_name')},
        ),
        migrations.AddIndex(
            model_name='smartprojectdocument',
            index=models.Index(fields=['project', 'discipline', 'document_type'], name='core_smart__project_0dbf35_idx'),
        ),
        migrations.AddIndex(
            model_name='smartprojectdocument',
            index=models.Index(fields=['content_hash'], name='core_smart__content_f466cf_idx'),
        ),
        migrations.AddIndex(
            model_name='smartprojectdocument',
            index=models.Index(fields=['uploaded_by', 'upload_date'], name='core_smart__uploade_f5a36f_idx'),
        ),
        migrations.AddIndex(
            model_name='smartprojectdocument',
            index=models.Index(fields=['document_category', 'is_active'], name='core_smart__documen_2712be_idx'),
        ),
        migrations.AddIndex(
            model_name='smartprojectdocument',
            index=models.Index(fields=['ai_classification_confidence'], name='core_smart__ai_clas_9e6f08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentrelationship',
            unique_together={('from_document', 'to_document', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='crossdisciplinerecommendation',
            index=models.Index(fields=['project', 'status'], name='core_cross__project_fe2177_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdisciplinerecommendation',
            index=models.Index(fields=['source_discipline', 'target_discipline'], name='core_cross__source__adbfa8_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdisciplinerecommendation',
            index=models.Index(fields=['recommendation_type', 'created_at'], name='core_cross__recomme_67fdd4_idx'),
        ),
    ]
