# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_recommendation', '0001_initial'),
    ]

    operations = [
        # Conditional rename: safe if index does not exist in production
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_source__e59eca_idx') THEN
                        ALTER INDEX cross_recom_source__e59eca_idx RENAME TO cross_recom_source__fedb83_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_target__7d77b4_idx') THEN
                        ALTER INDEX cross_recom_target__7d77b4_idx RENAME TO cross_recom_target__4d2a9e_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_project_6d8f4f_idx') THEN
                        ALTER INDEX cross_recom_project_6d8f4f_idx RENAME TO cross_recom_project_ed1a64_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_decisio_2e9d00_idx') THEN
                        ALTER INDEX cross_recom_decisio_2e9d00_idx RENAME TO cross_recom_decisio_e81fbf_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
