# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrench_integration', '0005_wrenchconfig_pre_shared_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrenchconfig',
            name='pre_shared_token',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted Wrench session token (pre-shared from the Wrench team). When non-empty, this token is used directly — bypassing the username/password login flow. The rolling refresh from each API response keeps it current. Never stored in plaintext.'),
        ),
    ]
