# Generated by Django 5.0 on 2026-05-22 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IOListDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('document_number', models.CharField(blank=True, default='', max_length=255)),
                ('revision_label', models.CharField(blank=True, default='', max_length=20)),
                ('plant', models.CharField(blank=True, default='', max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=60)),
                ('pdf_file', models.FileField(upload_to='instrument_io_workflow/%Y/%m/')),
                ('pdf_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('extraction_stats', models.JSONField(blank=True, default=dict)),
                ('extraction_error', models.TextField(blank=True, default='')),
                ('crs_chain_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='io_list_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IOListExtractedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(blank=True, default='', max_length=40)),
                ('company_comment', models.TextField(blank=True, default='')),
                ('contractor_reply', models.TextField(blank=True, default='')),
                ('company_decision', models.TextField(blank=True, default='')),
                ('status_code', models.CharField(blank=True, default='', max_length=20)),
                ('status_meaning', models.CharField(blank=True, default='', max_length=120)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('linked_tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_comments', to='instrument_io_workflow.iolistdocument')),
            ],
            options={
                'ordering': ['document_id', 'page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IOListExtractedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_rows', to='instrument_io_workflow.iolistdocument')),
            ],
            options={
                'ordering': ['document_id', 'page_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='iolistdocument',
            index=models.Index(fields=['pdf_sha256'], name='instrument__pdf_sha_98e8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='iolistdocument',
            index=models.Index(fields=['crs_chain_id'], name='instrument__crs_cha_41ce6b_idx'),
        ),
        migrations.AddIndex(
            model_name='iolistdocument',
            index=models.Index(fields=['document_number', 'revision_label'], name='instrument__documen_9a1515_idx'),
        ),
        migrations.AddIndex(
            model_name='iolistextractedrow',
            index=models.Index(fields=['tag_number'], name='instrument__tag_num_8502b5_idx'),
        ),
    ]
