# Generated by Django 5.0 on 2026-07-02 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_set_default_password_change_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_name',
            field=models.CharField(blank=True, help_text='Active Directory account name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='candidate_id',
            field=models.CharField(blank=True, help_text='Candidate ID from recruitment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_number',
            field=models.CharField(blank=True, db_index=True, help_text='Employee number from HR system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Employment ID from HRM system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hrm_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='implementation_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_test_person',
            field=models.BooleanField(default=False, help_text='Test person flag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title_finland',
            field=models.CharField(blank=True, help_text='Job title for Finland', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title_uae',
            field=models.CharField(blank=True, help_text='Job title for UAE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Direct manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='not_signed',
            field=models.BooleanField(default=False, help_text='Not signed flag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_given_name',
            field=models.CharField(blank=True, help_text='Preferred first name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='process_testing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='protected_identity',
            field=models.BooleanField(default=False, help_text='Protected identity flag'),
        ),
    ]
