# Generated by Django 5.0 on 2026-07-02 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('reporting_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(choices=[('RAD', 'Rejlers Abu Dhabi'), ('RIN', 'Rejlers India')], default='RAD', max_length=50)),
                ('exit_reason', models.CharField(choices=[('resignation', 'Voluntary Resignation'), ('termination', 'Termination'), ('contract_end', 'Contract Completion'), ('retirement', 'Retirement'), ('relocation', 'Relocation'), ('health', 'Health Reasons'), ('performance', 'Performance Issues'), ('redundancy', 'Redundancy'), ('other', 'Other')], max_length=50)),
                ('exit_reason_detail', models.TextField(blank=True, null=True)),
                ('last_working_day', models.DateField()),
                ('notice_period_days', models.IntegerField(default=30)),
                ('initiated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('access_revocation', 'Access Revocation'), ('equipment_return', 'Equipment Return'), ('exit_interview', 'Exit Interview'), ('final_settlement', 'Final Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('reporting_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(choices=[('RAD', 'Rejlers Abu Dhabi'), ('RIN', 'Rejlers India')], default='RAD', max_length=50)),
                ('joining_date', models.DateField()),
                ('initiated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('documentation', 'Documentation Collection'), ('equipment', 'Equipment Assignment'), ('access_provisioning', 'Access Provisioning'), ('training', 'Training & Orientation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headset', 'Headset'), ('mobile', 'Mobile Phone'), ('access_card', 'Access Card'), ('badge', 'ID Badge'), ('keys', 'Office Keys'), ('other', 'Other')], max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='onboarding.offboardingrecord')),
                ('onboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='onboarding.onboardingrecord')),
            ],
            options={
                'db_table': 'onboarding_equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport Copy'), ('visa', 'Visa/Emirates ID'), ('degree', 'Educational Certificates'), ('experience', 'Experience Letters'), ('offer_letter', 'Signed Offer Letter'), ('contract', 'Employment Contract'), ('confidentiality', 'Confidentiality Agreement'), ('policy_acknowledgment', 'Policy Acknowledgment'), ('bank_details', 'Bank Account Details'), ('emergency_contact', 'Emergency Contact Form'), ('medical', 'Medical/Insurance Forms'), ('resignation', 'Resignation Letter'), ('clearance', 'Exit Clearance Form'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('offboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.offboardingrecord')),
                ('onboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboardingrecord')),
            ],
            options={
                'db_table': 'onboarding_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_completed', to=settings.AUTH_USER_MODEL)),
                ('offboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.offboardingrecord')),
                ('onboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.onboardingrecord')),
            ],
            options={
                'db_table': 'onboarding_checklist',
                'ordering': ['due_date', '-priority', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('email', 'Email Account'), ('active_directory', 'Active Directory'), ('erp', 'ERP System'), ('hr_system', 'HR System'), ('project_tools', 'Project Management Tools'), ('cloud_storage', 'Cloud Storage'), ('vpn', 'VPN Access'), ('building_access', 'Building Access'), ('parking', 'Parking Access'), ('other', 'Other')], max_length=50)),
                ('access_name', models.CharField(max_length=255)),
                ('account_username', models.CharField(blank=True, max_length=255, null=True)),
                ('provisioned', models.BooleanField(default=False)),
                ('provisioned_date', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_assigned', to=settings.AUTH_USER_MODEL)),
                ('offboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='onboarding.offboardingrecord')),
                ('onboarding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='onboarding.onboardingrecord')),
            ],
            options={
                'db_table': 'onboarding_access',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offboardingrecord',
            index=models.Index(fields=['status'], name='offboarding_status_62ca82_idx'),
        ),
        migrations.AddIndex(
            model_name='offboardingrecord',
            index=models.Index(fields=['last_working_day'], name='offboarding_last_wo_cea804_idx'),
        ),
        migrations.AddIndex(
            model_name='offboardingrecord',
            index=models.Index(fields=['employee_email'], name='offboarding_employe_410f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingrecord',
            index=models.Index(fields=['status'], name='onboarding__status_08ddbf_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingrecord',
            index=models.Index(fields=['joining_date'], name='onboarding__joining_c438ea_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingrecord',
            index=models.Index(fields=['employee_email'], name='onboarding__employe_4c3114_idx'),
        ),
    ]
