# Generated by Django 4.2.16 on 2026-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, help_text='Presigned URL or public URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport Copy'), ('visa', 'Visa'), ('emirates_id', 'Emirates ID'), ('driving_license', 'Driving License'), ('degree', 'Educational Certificates'), ('certificate', 'Professional Certificate'), ('experience', 'Experience Letters'), ('offer_letter', 'Signed Offer Letter'), ('contract', 'Employment Contract'), ('confidentiality', 'Confidentiality Agreement'), ('policy_acknowledgment', 'Policy Acknowledgment'), ('bank_details', 'Bank Account Details'), ('emergency_contact', 'Emergency Contact Form'), ('medical', 'Medical/Insurance Forms'), ('vaccination', 'Vaccination Certificate'), ('police_clearance', 'Police Clearance Certificate'), ('resignation', 'Resignation Letter'), ('clearance', 'Exit Clearance Form'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, help_text='S3 key path for the uploaded file', max_length=500, null=True),
        ),
    ]
