# Generated by Django 4.2.16 on 2026-07-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_document_file_mime_type_document_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrecord',
            name='photo_file_path',
            field=models.CharField(blank=True, help_text='S3 key for passport photo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='photo_file_size',
            field=models.IntegerField(blank=True, help_text='Photo file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='photo_mime_type',
            field=models.CharField(blank=True, help_text='Photo MIME type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='photo_original_filename',
            field=models.CharField(blank=True, help_text='Original photo filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Presigned S3 URL for photo', max_length=1000, null=True),
        ),
    ]
