# Generated by Django 4.2.30 on 2026-08-18 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0008_offboarding_project_manager_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='offboardingrecord',
            name='approval_workflow_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('project_managers_pending', 'Awaiting Project Manager(s) Approval'), ('hr_coordinator_pending', 'Awaiting HR Coordinator Approval'), ('hr_approver_pending', 'Awaiting HR Approver'), ('approved', 'Fully Approved'), ('rejected', 'Rejected')], db_index=True, default='not_started', help_text='Current stage in the three-step approval workflow', max_length=30),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_approver',
            field=models.ForeignKey(blank=True, help_text='HR Manager/Approver for final exit approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_hr_approver_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_approver_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_approver_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_approver_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_coordinator',
            field=models.ForeignKey(blank=True, help_text='HR Coordinator responsible for processing exit documentation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_hr_coordinator_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_coordinator_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_coordinator_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offboardingrecord',
            name='hr_coordinator_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='stage',
            field=models.CharField(choices=[('general', 'General'), ('pre_hire', 'Pre-Hire Initiation'), ('it_provisioning', 'IT Provisioning'), ('first_day', 'First Day Orientation'), ('final_validation', 'Final Checklist Validation'), ('exit_initiation', 'Exit Initiation'), ('access_revocation', 'Access Revocation'), ('asset_return', 'Asset Return'), ('exit_clearance', 'Exit Interview & Clearance'), ('final_settlement', 'Final Settlement')], db_index=True, default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='ExitApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_step', models.CharField(choices=[('project_manager', 'Project Manager'), ('hr_coordinator', 'HR Coordinator'), ('hr_approver', 'HR Approver')], db_index=True, help_text='Which step in the approval workflow this record represents', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('decision_note', models.TextField(blank=True, help_text='Optional note/reason from the approver', null=True)),
                ('decided_at', models.DateTimeField(blank=True, help_text='Timestamp when the approval decision was made', null=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether approval request notification was sent to approver')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_count', models.IntegerField(default=0, help_text='Number of reminder notifications sent')),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='User assigned to approve this exit (Project Manager, HR Coordinator, or HR Approver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_approval_assignments', to=settings.AUTH_USER_MODEL)),
                ('offboarding_record', models.ForeignKey(help_text='The offboarding record requiring approval', on_delete=django.db.models.deletion.CASCADE, related_name='exit_approvals', to='onboarding.offboardingrecord')),
            ],
            options={
                'db_table': 'exit_approval',
                'ordering': ['offboarding_record', 'approval_step', 'created_at'],
                'indexes': [models.Index(fields=['offboarding_record', 'approval_step'], name='exit_approv_offboar_19e862_idx'), models.Index(fields=['approver', 'status'], name='exit_approv_approve_bd071c_idx'), models.Index(fields=['status', 'created_at'], name='exit_approv_status_73f3a5_idx')],
                'unique_together': {('offboarding_record', 'approver', 'approval_step')},
            },
        ),
    ]
