# Generated by Django 4.2.30 on 2026-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_offboardingrecord_approval_workflow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitapproval',
            name='project_name',
            field=models.CharField(blank=True, help_text='Project name for better readability', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exitapproval',
            name='project_number',
            field=models.CharField(blank=True, help_text='Project number/code this approval is for (when employee is assigned to multiple projects)', max_length=100, null=True),
        ),
    ]
