# Generated by Django 5.0 on 2026-05-05 07:21

import apps.electrical_datasheet.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_datasheet', '0003_excel_quality_checker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetmetadata',
            name='document',
        ),
        migrations.RemoveField(
            model_name='uploadedexceldocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='validationissue',
            name='document',
        ),
        migrations.RemoveField(
            model_name='validationissue',
            name='acknowledged_by',
        ),
        migrations.RemoveField(
            model_name='electricaldatasheet',
            name='compliance_score',
        ),
        migrations.RemoveField(
            model_name='electricaldatasheet',
            name='last_quality_check',
        ),
        migrations.CreateModel(
            name='GeneratedDatasheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(choices=[('transformer', 'Power / Distribution Transformer'), ('dg_set', 'Emergency Diesel Generator Set'), ('mv_switchgear', '11KV Switchgear')], db_index=True, max_length=32)),
                ('variant', models.CharField(choices=[('power', 'Power (e.g. 25 MVA)'), ('distribution', 'Distribution (e.g. 1.25 MVA)'), ('default', 'Default')], default='default', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('revision', models.CharField(default='A', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('issued', 'Issued'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('rows', models.JSONField(default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_files', models.JSONField(blank=True, default=list)),
                ('excel_s3_key', models.CharField(blank=True, max_length=512)),
                ('pdf_s3_key', models.CharField(blank=True, max_length=512)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_datasheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Datasheet',
                'verbose_name_plural': 'Generated Datasheets',
                'db_table': 'electrical_generated_datasheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetShareLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=apps.electrical_datasheet.models._share_token_default, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='electrical_datasheet.generateddatasheet')),
            ],
            options={
                'db_table': 'electrical_datasheet_share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetCellEdit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('column_key', models.CharField(max_length=32)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual edit'), ('recheck', 'Applied from recheck'), ('ai_suggest', 'AI suggestion'), ('revert', 'Revision revert')], default='manual', max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_edits', to='electrical_datasheet.generateddatasheet')),
            ],
            options={
                'db_table': 'electrical_datasheet_cell_edits',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDatasheetCellComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('column_key', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_comments', to='electrical_datasheet.generateddatasheet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_datasheet_cell_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electrical_generated_datasheet_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDatasheetRevision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revision_label', models.CharField(max_length=16)),
                ('rows', models.JSONField(default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='electrical_datasheet.generateddatasheet')),
            ],
            options={
                'db_table': 'electrical_generated_datasheet_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ParsedItem',
        ),
        migrations.DeleteModel(
            name='SheetMetadata',
        ),
        migrations.DeleteModel(
            name='UploadedExcelDocument',
        ),
        migrations.DeleteModel(
            name='ValidationIssue',
        ),
        migrations.AddIndex(
            model_name='generateddatasheet',
            index=models.Index(fields=['user', 'equipment_type', '-created_at'], name='electrical__user_id_fd012a_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddatasheet',
            index=models.Index(fields=['user', 'is_archived'], name='electrical__user_id_bf3685_idx'),
        ),
        migrations.AddIndex(
            model_name='datasheetcelledit',
            index=models.Index(fields=['datasheet', 'row_index'], name='electrical__datashe_683e31_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddatasheetcellcomment',
            index=models.Index(fields=['datasheet', 'row_index'], name='electrical__datashe_369231_idx'),
        ),
    ]
