# Generated by Django 5.0 on 2026-06-23 05:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0018_default_access_and_hr_self_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='Why does the user need access to this module?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text='Admin response or reason for denial')),
            ],
            options={
                'verbose_name': 'Access Request',
                'verbose_name_plural': 'Access Requests',
                'db_table': 'rbac_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_user_id_f3fd17_idx',
            old_name='activity_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_applica_be833b_idx',
            old_name='activity_app_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_feature_849538_idx',
            old_name='activity_feat_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aipricingconfig',
            new_name='ai_pricing__provide_ed408d_idx',
            old_name='ai_pricing_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_user_id_48fed7_idx',
            old_name='ai_usage_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_provide_32aae3_idx',
            old_name='ai_usage_prov_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_applica_3a99b4_idx',
            old_name='ai_usage_app_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_timesta_abde11_idx',
            old_name='ai_usage_ts_success_idx',
        ),
        migrations.RenameIndex(
            model_name='engineerprofile',
            new_name='rbac_engine_experti_dfb74c_idx',
            old_name='rbac_ep_expertise_idx',
        ),
        migrations.RenameIndex(
            model_name='engineerprofile',
            new_name='rbac_engine_availab_84cf7e_idx',
            old_name='rbac_ep_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlychampion',
            new_name='monthly_cha_period__237888_idx',
            old_name='champion_period_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlychampion',
            new_name='monthly_cha_user_id_769211_idx',
            old_name='champion_user_period_idx',
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aipricingconfig',
            name='effective_from',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='rbac.module'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='rbac.userprofile'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['user_profile', 'status'], name='rbac_access_user_pr_03b62e_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['module', 'status'], name='rbac_access_module__490219_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status', '-created_at'], name='rbac_access_status_282f8e_idx'),
        ),
    ]
