# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0028_replace_viewer_with_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.IntegerField(choices=[(1, 'Super Administrator'), (2, 'Admin'), (3, 'Manager'), (4, 'Engineer'), (5, 'Reviewer'), (6, 'Viewer')], default=6),
        ),
    ]
