# Generated by Django - Manual Migration for Data Mining Module
# This migration ensures data_mining module exists and is assigned to all relevant roles
# Uses soft-coded configuration from rbac_config.py

from django.db import migrations


def seed_data_mining_module(apps, schema_editor):
    """
    Seed data_mining module using soft-coded configuration.
    This runs automatically on Railway deployment via migrate command.
    """
    Module = apps.get_model('rbac', 'Module')
    Role = apps.get_model('rbac', 'Role')
    
    # Soft-coded module configuration
    data_mining_config = {
        'code': 'data_mining',
        'name': 'Data Mining Platform',
        'icon': 'TableCells',
        'order': 6,
        'description': 'Tableau Prep-style data transformation and master file generation',
        'is_active': True,
    }
    
    # Create or update module
    module, created = Module.objects.update_or_create(
        code=data_mining_config['code'],
        defaults={
            'name': data_mining_config['name'],
            'icon': data_mining_config['icon'],
            'order': data_mining_config['order'],
            'description': data_mining_config['description'],
            'is_active': data_mining_config['is_active'],
        }
    )
    
    action = "Created" if created else "Updated"
    print(f"✅ {action} module: {module.name} (code={module.code}, id={module.id})")
    
    # Soft-coded list of roles that should have data_mining module
    # Matches DEFAULT_ROLE_MODULES and ENGINEERING_SECTION_MODULES in rbac_config.py
    roles_with_data_mining = [
        'default',           # All users
        'super_admin',       # Super Administrator
        'admin',             # Administrator
        'process_engineer',  # Process Engineering
        'piping_engineer',   # Piping Engineering
        'electrical_engineer',  # Electrical Engineering
        'instrument_engineer',  # Instrument Engineering
        'mechanical_engineer',  # Mechanical Engineering
        'civil_engineer',       # Civil Engineering
    ]
    
    assigned_count = 0
    for role_code in roles_with_data_mining:
        try:
            role = Role.objects.get(code=role_code)
            if not role.modules.filter(code='data_mining').exists():
                role.modules.add(module)
                print(f"  → Assigned data_mining to role: {role.name} ({role.code})")
                assigned_count += 1
            else:
                print(f"  ✓ Already assigned to: {role.name} ({role.code})")
        except Role.DoesNotExist:
            print(f"  ⚠️  Role not found: {role_code}")
            continue
    
    if assigned_count > 0:
        print(f"✅ Assigned data_mining module to {assigned_count} roles")
    
    print("=" * 60)
    print(f"Data Mining Module Migration Complete")
    print(f"Module ID: {module.id}, Active: {module.is_active}")
    print("=" * 60)


def reverse_seed(apps, schema_editor):
    """
    Reverse: Remove data_mining module assignments (but keep the module)
    """
    Module = apps.get_model('rbac', 'Module')
    try:
        module = Module.objects.get(code='data_mining')
        count = module.roles.count()
        module.roles.clear()
        print(f"⏪ Removed data_mining from {count} roles")
    except Module.DoesNotExist:
        print("⏪ data_mining module does not exist")


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0029_alter_role_level'),
    ]

    operations = [
        migrations.RunPython(seed_data_mining_module, reverse_seed),
    ]
