# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'usage_log_ts_disc_idx') THEN
                        ALTER INDEX usage_log_ts_disc_idx RENAME TO usage_log_timesta_74eff2_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'usage_log_email_ts_idx') THEN
                        ALTER INDEX usage_log_email_ts_idx RENAME TO usage_log_user_em_75b9a8_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
