# Generated by Django 5.0 on 2026-06-16 09:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_add_salary_slip_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsightSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('attendance_anomaly', 'Attendance Anomaly'), ('missing_timesheet', 'Missing Timesheet'), ('overtime_alert', 'Overtime Alert'), ('payroll_risk', 'Payroll Risk Score'), ('burnout_risk', 'Burnout Risk'), ('productivity_trend', 'Productivity Trend'), ('payroll_forecast', 'Payroll Forecast')], max_length=32)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('employee_salary_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='finance.employeesalaryinfo')),
            ],
            options={
                'db_table': 'payroll_ai_insight_snapshot',
                'ordering': ['-year', '-month', 'insight_type'],
                'indexes': [models.Index(fields=['employee_salary_info', 'year', 'month'], name='payroll_ai__employe_483459_idx')],
                'unique_together': {('employee_salary_info', 'month', 'year', 'insight_type')},
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, help_text='Matched intent key from rule engine', max_length=64)),
                ('data_payload', models.JSONField(blank=True, default=dict, help_text='Structured data returned with response')),
                ('persona', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('finance', 'Finance'), ('hr', 'HR')], default='employee', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_chatbot_message',
                'ordering': ['session_id', 'created_at'],
                'indexes': [models.Index(fields=['user', 'session_id'], name='payroll_cha_user_id_2ddeda_idx'), models.Index(fields=['session_id', 'created_at'], name='payroll_cha_session_d3e644_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollAuditAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('salary_spike', 'Salary Spike'), ('new_employee', 'New Employee'), ('missing_employee', 'Missing Employee'), ('overtime_excess', 'Overtime Excess'), ('negative_salary', 'Negative Salary'), ('duplicate_payment', 'Duplicate Payment Risk')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('suggested_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('compared_to_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compared_alerts', to='finance.payrollrun')),
                ('employee_salary_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_alerts', to='finance.employeesalaryinfo')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_alerts', to='finance.payrollrun')),
            ],
            options={
                'db_table': 'payroll_audit_alert',
                'ordering': ['-created_at', 'severity'],
                'indexes': [models.Index(fields=['payroll_run', 'status'], name='payroll_aud_payroll_17d07c_idx'), models.Index(fields=['payroll_run', 'alert_type'], name='payroll_aud_payroll_9d0c74_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=64)),
                ('rule_label', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_salary_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='finance.employeesalaryinfo')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='finance.payrollrun')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_validation_log',
                'ordering': ['-created_at', 'severity'],
                'indexes': [models.Index(fields=['payroll_run', 'severity'], name='payroll_val_payroll_2df5fb_idx'), models.Index(fields=['payroll_run', 'is_resolved'], name='payroll_val_payroll_14a729_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCostAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=64)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=64)),
                ('allocated_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('allocation_percent', models.DecimalField(decimal_places=2, help_text='Percentage of salary allocated to this project (0–100)', max_digits=6)),
                ('allocated_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='finance.salaryslip')),
            ],
            options={
                'db_table': 'payroll_project_cost_allocation',
                'ordering': ['year', 'month', 'project_code'],
                'indexes': [models.Index(fields=['project_code', 'year', 'month'], name='payroll_pro_project_bf6d2b_idx'), models.Index(fields=['salary_slip'], name='payroll_pro_salary__f0867e_idx')],
            },
        ),
    ]
