# Generated by Django 5.0 on 2026-06-16 10:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('employee_name', models.CharField(db_index=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('annual_entitlement', models.DecimalField(decimal_places=2, default=Decimal('22'), max_digits=6)),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('total_earned', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('total_taken', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('total_encashed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('leave_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('carryforward', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_employee_leave_record',
                'ordering': ['employee_name'],
                'indexes': [models.Index(fields=['year', 'department'], name='payroll_emp_year_481da0_idx'), models.Index(fields=['employee_code'], name='payroll_emp_employe_bb7e67_idx')],
                'unique_together': {('employee_code', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveMonthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('earned', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('taken', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('encashed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_breakdown', to='payroll.employeeleaverecord')),
            ],
            options={
                'db_table': 'payroll_employee_leave_monthly',
                'ordering': ['record', 'month'],
                'unique_together': {('record', 'month')},
            },
        ),
    ]
