# Generated by Django 5.0 on 2026-06-19 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_normalize_employee_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField(db_index=True)),
                ('task_title', models.CharField(max_length=255)),
                ('project_category', models.CharField(blank=True, max_length=100)),
                ('hours_spent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('deferred', 'Deferred')], db_index=True, default='in_progress', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('s3_export_key', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_daily_work_log',
                'ordering': ['-log_date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='publicholiday',
            name='payroll_ph_date_region_uniq',
        ),
        migrations.AlterField(
            model_name='attendanceoverride',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Only the most-recent active override for a given (employee_code, date) is applied.'),
        ),
        migrations.AlterField(
            model_name='attendanceoverride',
            name='note',
            field=models.TextField(blank=True, help_text='Free-text HR note explaining the correction.'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='color_hex',
            field=models.CharField(default='#6b7280', help_text='Hex colour for charts and calendar heatmap', max_length=7),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Deactivate without deleting — keeps audit trail intact.'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic name (optional — for display purposes only).', max_length=255),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='note',
            field=models.TextField(blank=True, help_text='HR note, e.g. confirmed date, subject to moon sighting, etc.'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='source',
            field=models.CharField(choices=[('government', 'Abu Dhabi Government Official Calendar'), ('hr_added', 'Added by HR Manager')], default='government', help_text='Whether this entry came from the official calendar or was added by HR.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('date', 'region')},
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyworklog',
            index=models.Index(fields=['user', 'log_date'], name='payroll_dwl_user_date'),
        ),
        migrations.AddIndex(
            model_name='dailyworklog',
            index=models.Index(fields=['log_date'], name='payroll_dwl_date'),
        ),
        migrations.AddIndex(
            model_name='dailyworklog',
            index=models.Index(fields=['status'], name='payroll_dwl_status'),
        ),
    ]
