# Generated by Django 5.0 on 2026-06-19 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_salary_slip_models'),
        ('payroll', '0008_add_daily_work_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworklog',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcostallocation',
            name='salary_slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='finance.salaryslip'),
        ),
        migrations.AddIndex(
            model_name='dailyworklog',
            index=models.Index(fields=['approval_status'], name='payroll_dwl_approval'),
        ),
    ]
