# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_leave_rm_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpayrollimport',
            name='finance_approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masterpayrollimport',
            name='hr_approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masterpayrollimport',
            name='month',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='masterpayrollimport',
            name='release_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masterpayrollimport',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('uploaded', 'Uploaded to S3'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='masterpayrollimport',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='masterpayrollrow',
            name='employee_code',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
