# Generated by Django 4.2.16 on 2026-07-02 08:35

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_alter_masterpayrollimport_finance_approval_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeaveAccrualLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(help_text='Year processed (e.g., 2026)')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month processed (1=January, 12=December)')),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of execution')),
                ('triggered_by', models.CharField(default='celery_beat', help_text='Source: celery_beat (auto) | manual (admin) | api (HR Manager)', max_length=50)),
                ('records_processed', models.PositiveIntegerField(default=0, help_text='Total employee records examined')),
                ('records_created', models.PositiveIntegerField(default=0, help_text='New monthly records created')),
                ('records_updated', models.PositiveIntegerField(default=0, help_text='Existing records updated')),
                ('monthly_accrual_used', models.DecimalField(decimal_places=4, default=Decimal('1.8333'), help_text='Monthly accrual value used for this run', max_digits=8)),
                ('branch_filter', models.CharField(blank=True, help_text='Branch code filter (null = all branches)', max_length=10, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='success', help_text='Execution outcome', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status=failed')),
            ],
            options={
                'db_table': 'payroll_monthly_leave_accrual_log',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['year', 'month'], name='payroll_mon_year_39e33c_idx'), models.Index(fields=['executed_at'], name='payroll_mon_execute_0c0f81_idx')],
                'unique_together': {('year', 'month', 'triggered_by')},
            },
        ),
    ]
