# Generated by Django 5.0 on 2026-07-01 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designiq', '0002_engineeringlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPIDOutput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid_number', models.CharField(db_index=True, max_length=200)),
                ('pid_revision', models.CharField(blank=True, max_length=50)),
                ('list_type', models.CharField(db_index=True, default='line_list', max_length=50)),
                ('document_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('processing_date', models.DateTimeField(auto_now_add=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='designiq/processed_outputs/%Y/%m/')),
                ('excel_filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('total_lines', models.IntegerField(default=0)),
                ('total_columns', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0)),
                ('format_type', models.CharField(default='general', max_length=50)),
                ('include_area', models.BooleanField(default=False)),
                ('enrichment_enabled', models.BooleanField(default=False)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_outputs', to='designiq.designproject')),
            ],
            options={
                'db_table': 'designiq_processed_pid_outputs',
                'ordering': ['-processing_date'],
                'indexes': [models.Index(fields=['pid_number', '-processing_date'], name='designiq_pr_pid_num_5f51cc_idx'), models.Index(fields=['list_type', '-processing_date'], name='designiq_pr_list_ty_cf28cc_idx'), models.Index(fields=['document_id'], name='designiq_pr_documen_787c7c_idx')],
            },
        ),
    ]
